// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package postgres

import (
	"context"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializePostgres(ctx context.Context, dns PostgresConnectionString) *gorm.DB {
	gormDB := newPostgresGorm(ctx, dns)
	return gormDB
}
