// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package clickhouse

import (
	"context"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeClickhouse(ctx context.Context, opt ConnectionOpt) *gorm.DB {
	gormDB := newClickhouseGorm(ctx, opt)
	return gormDB
}
