// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package redis

import (
	"context"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializeRedis(ctx context.Context, dns RedisConnectionString) *redis.Client {
	client := newRedisClient(ctx, dns)
	return client
}
